// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/management/device.proto

package ai.sensorycloud.api.v1.management;

public interface DeviceListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.v1.management.DeviceListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of devices
   * </pre>
   *
   * <code>repeated .sensory.api.v1.management.DeviceResponse devices = 1;</code>
   */
  java.util.List<ai.sensorycloud.api.v1.management.DeviceResponse> 
      getDevicesList();
  /**
   * <pre>
   * A list of devices
   * </pre>
   *
   * <code>repeated .sensory.api.v1.management.DeviceResponse devices = 1;</code>
   */
  ai.sensorycloud.api.v1.management.DeviceResponse getDevices(int index);
  /**
   * <pre>
   * A list of devices
   * </pre>
   *
   * <code>repeated .sensory.api.v1.management.DeviceResponse devices = 1;</code>
   */
  int getDevicesCount();
  /**
   * <pre>
   * A list of devices
   * </pre>
   *
   * <code>repeated .sensory.api.v1.management.DeviceResponse devices = 1;</code>
   */
  java.util.List<? extends ai.sensorycloud.api.v1.management.DeviceResponseOrBuilder> 
      getDevicesOrBuilderList();
  /**
   * <pre>
   * A list of devices
   * </pre>
   *
   * <code>repeated .sensory.api.v1.management.DeviceResponse devices = 1;</code>
   */
  ai.sensorycloud.api.v1.management.DeviceResponseOrBuilder getDevicesOrBuilder(
      int index);

  /**
   * <pre>
   * Metadata about how the response has been paginated
   * </pre>
   *
   * <code>.sensory.api.common.PaginationResponse pagination = 2;</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <pre>
   * Metadata about how the response has been paginated
   * </pre>
   *
   * <code>.sensory.api.common.PaginationResponse pagination = 2;</code>
   * @return The pagination.
   */
  ai.sensorycloud.api.common.PaginationResponse getPagination();
  /**
   * <pre>
   * Metadata about how the response has been paginated
   * </pre>
   *
   * <code>.sensory.api.common.PaginationResponse pagination = 2;</code>
   */
  ai.sensorycloud.api.common.PaginationResponseOrBuilder getPaginationOrBuilder();
}
