// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/management/device.proto

package ai.sensorycloud.api.v1.management;

public interface DeviceGetWhoAmIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.v1.management.DeviceGetWhoAmIRequest)
    com.google.protobuf.MessageOrBuilder {
}
