// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/management/device.proto

package ai.sensorycloud.api.v1.management;

/**
 * <pre>
 * Request to enroll a new device in the system. Devices can then enroll and associate users with themselves.
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.management.EnrollDeviceRequest}
 */
public final class EnrollDeviceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.management.EnrollDeviceRequest)
    EnrollDeviceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnrollDeviceRequest.newBuilder() to construct.
  private EnrollDeviceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnrollDeviceRequest() {
    name_ = "";
    deviceId_ = "";
    tenantId_ = "";
    credential_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnrollDeviceRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnrollDeviceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          case 34: {
            ai.sensorycloud.api.common.GenericClient.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(ai.sensorycloud.api.common.GenericClient.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            credential_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sensorycloud.api.v1.management.SensoryApiV1ManagementDeviceProto.internal_static_sensory_api_v1_management_EnrollDeviceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sensorycloud.api.v1.management.SensoryApiV1ManagementDeviceProto.internal_static_sensory_api_v1_management_EnrollDeviceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sensorycloud.api.v1.management.EnrollDeviceRequest.class, ai.sensorycloud.api.v1.management.EnrollDeviceRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The friendly name you'd like to associate with this device
   * </pre>
   *
   * <code>string name = 1 [(.validate.rules) = { ... }</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The friendly name you'd like to associate with this device
   * </pre>
   *
   * <code>string name = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceId_;
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
   * A typical value would be a hardware serial number.
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANTID_FIELD_NUMBER = 3;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique Tenant ID as UUID
   * </pre>
   *
   * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_FIELD_NUMBER = 4;
  private ai.sensorycloud.api.common.GenericClient client_;
  /**
   * <pre>
   * OAuth client-specific request details
   * </pre>
   *
   * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
   * @return Whether the client field is set.
   */
  @java.lang.Override
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <pre>
   * OAuth client-specific request details
   * </pre>
   *
   * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
   * @return The client.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.GenericClient getClient() {
    return client_ == null ? ai.sensorycloud.api.common.GenericClient.getDefaultInstance() : client_;
  }
  /**
   * <pre>
   * OAuth client-specific request details
   * </pre>
   *
   * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.GenericClientOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int CREDENTIAL_FIELD_NUMBER = 5;
  private volatile java.lang.Object credential_;
  /**
   * <pre>
   * If required, the credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 5;</code>
   * @return The credential.
   */
  @java.lang.Override
  public java.lang.String getCredential() {
    java.lang.Object ref = credential_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      credential_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * If required, the credential to be validated by the server upon enrollment.
   * Possible values are a shared secret or signed JWT.
   * </pre>
   *
   * <code>string credential = 5;</code>
   * @return The bytes for credential.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCredentialBytes() {
    java.lang.Object ref = credential_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      credential_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tenantId_);
    }
    if (client_ != null) {
      output.writeMessage(4, getClient());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(credential_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, credential_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tenantId_);
    }
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getClient());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(credential_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, credential_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sensorycloud.api.v1.management.EnrollDeviceRequest)) {
      return super.equals(obj);
    }
    ai.sensorycloud.api.v1.management.EnrollDeviceRequest other = (ai.sensorycloud.api.v1.management.EnrollDeviceRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (!getClient()
          .equals(other.getClient())) return false;
    }
    if (!getCredential()
        .equals(other.getCredential())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    hash = (37 * hash) + CREDENTIAL_FIELD_NUMBER;
    hash = (53 * hash) + getCredential().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.management.EnrollDeviceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to enroll a new device in the system. Devices can then enroll and associate users with themselves.
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.management.EnrollDeviceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.management.EnrollDeviceRequest)
      ai.sensorycloud.api.v1.management.EnrollDeviceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sensorycloud.api.v1.management.SensoryApiV1ManagementDeviceProto.internal_static_sensory_api_v1_management_EnrollDeviceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sensorycloud.api.v1.management.SensoryApiV1ManagementDeviceProto.internal_static_sensory_api_v1_management_EnrollDeviceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sensorycloud.api.v1.management.EnrollDeviceRequest.class, ai.sensorycloud.api.v1.management.EnrollDeviceRequest.Builder.class);
    }

    // Construct using ai.sensorycloud.api.v1.management.EnrollDeviceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      deviceId_ = "";

      tenantId_ = "";

      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      credential_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sensorycloud.api.v1.management.SensoryApiV1ManagementDeviceProto.internal_static_sensory_api_v1_management_EnrollDeviceRequest_descriptor;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.management.EnrollDeviceRequest getDefaultInstanceForType() {
      return ai.sensorycloud.api.v1.management.EnrollDeviceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.management.EnrollDeviceRequest build() {
      ai.sensorycloud.api.v1.management.EnrollDeviceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.management.EnrollDeviceRequest buildPartial() {
      ai.sensorycloud.api.v1.management.EnrollDeviceRequest result = new ai.sensorycloud.api.v1.management.EnrollDeviceRequest(this);
      result.name_ = name_;
      result.deviceId_ = deviceId_;
      result.tenantId_ = tenantId_;
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      result.credential_ = credential_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sensorycloud.api.v1.management.EnrollDeviceRequest) {
        return mergeFrom((ai.sensorycloud.api.v1.management.EnrollDeviceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sensorycloud.api.v1.management.EnrollDeviceRequest other) {
      if (other == ai.sensorycloud.api.v1.management.EnrollDeviceRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (!other.getCredential().isEmpty()) {
        credential_ = other.credential_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sensorycloud.api.v1.management.EnrollDeviceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sensorycloud.api.v1.management.EnrollDeviceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The friendly name you'd like to associate with this device
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The friendly name you'd like to associate with this device
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The friendly name you'd like to associate with this device
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The friendly name you'd like to associate with this device
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The friendly name you'd like to associate with this device
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique internal identifier for this device. Ideally, this value is static for the lifetime of the device.
     * A typical value would be a hardware serial number.
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique Tenant ID as UUID
     * </pre>
     *
     * <code>string tenantId = 3 [(.validate.rules) = { ... }</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private ai.sensorycloud.api.common.GenericClient client_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.GenericClient, ai.sensorycloud.api.common.GenericClient.Builder, ai.sensorycloud.api.common.GenericClientOrBuilder> clientBuilder_;
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     * @return The client.
     */
    public ai.sensorycloud.api.common.GenericClient getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? ai.sensorycloud.api.common.GenericClient.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public Builder setClient(ai.sensorycloud.api.common.GenericClient value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public Builder setClient(
        ai.sensorycloud.api.common.GenericClient.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeClient(ai.sensorycloud.api.common.GenericClient value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            ai.sensorycloud.api.common.GenericClient.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.GenericClient.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.GenericClientOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            ai.sensorycloud.api.common.GenericClient.getDefaultInstance() : client_;
      }
    }
    /**
     * <pre>
     * OAuth client-specific request details
     * </pre>
     *
     * <code>.sensory.api.common.GenericClient client = 4 [(.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.GenericClient, ai.sensorycloud.api.common.GenericClient.Builder, ai.sensorycloud.api.common.GenericClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sensorycloud.api.common.GenericClient, ai.sensorycloud.api.common.GenericClient.Builder, ai.sensorycloud.api.common.GenericClientOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private java.lang.Object credential_ = "";
    /**
     * <pre>
     * If required, the credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 5;</code>
     * @return The credential.
     */
    public java.lang.String getCredential() {
      java.lang.Object ref = credential_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credential_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * If required, the credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 5;</code>
     * @return The bytes for credential.
     */
    public com.google.protobuf.ByteString
        getCredentialBytes() {
      java.lang.Object ref = credential_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credential_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * If required, the credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 5;</code>
     * @param value The credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredential(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      credential_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If required, the credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredential() {
      
      credential_ = getDefaultInstance().getCredential();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If required, the credential to be validated by the server upon enrollment.
     * Possible values are a shared secret or signed JWT.
     * </pre>
     *
     * <code>string credential = 5;</code>
     * @param value The bytes for credential to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      credential_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensory.api.v1.management.EnrollDeviceRequest)
  }

  // @@protoc_insertion_point(class_scope:sensory.api.v1.management.EnrollDeviceRequest)
  private static final ai.sensorycloud.api.v1.management.EnrollDeviceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sensorycloud.api.v1.management.EnrollDeviceRequest();
  }

  public static ai.sensorycloud.api.v1.management.EnrollDeviceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnrollDeviceRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnrollDeviceRequest>() {
    @java.lang.Override
    public EnrollDeviceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnrollDeviceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnrollDeviceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnrollDeviceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.sensorycloud.api.v1.management.EnrollDeviceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

