// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/event/event.proto

package ai.sensorycloud.api.v1.event;

/**
 * Protobuf type {@code sensory.api.v1.event.UsageEventModelSummary}
 */
public final class UsageEventModelSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.event.UsageEventModelSummary)
    UsageEventModelSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UsageEventModelSummary.newBuilder() to construct.
  private UsageEventModelSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UsageEventModelSummary() {
    billableFunction_ = 0;
    units_ = "";
    tenantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UsageEventModelSummary();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sensorycloud.api.v1.event.SensoryApiV1EventProto.internal_static_sensory_api_v1_event_UsageEventModelSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sensorycloud.api.v1.event.SensoryApiV1EventProto.internal_static_sensory_api_v1_event_UsageEventModelSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sensorycloud.api.v1.event.UsageEventModelSummary.class, ai.sensorycloud.api.v1.event.UsageEventModelSummary.Builder.class);
  }

  public static final int BILLABLEFUNCTION_FIELD_NUMBER = 1;
  private int billableFunction_ = 0;
  /**
   * <pre>
   * Function of the model used
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
   * @return The enum numeric value on the wire for billableFunction.
   */
  @java.lang.Override public int getBillableFunctionValue() {
    return billableFunction_;
  }
  /**
   * <pre>
   * Function of the model used
   * </pre>
   *
   * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
   * @return The billableFunction.
   */
  @java.lang.Override public ai.sensorycloud.api.common.ModelType getBillableFunction() {
    ai.sensorycloud.api.common.ModelType result = ai.sensorycloud.api.common.ModelType.forNumber(billableFunction_);
    return result == null ? ai.sensorycloud.api.common.ModelType.UNRECOGNIZED : result;
  }

  public static final int UNITS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object units_ = "";
  /**
   * <pre>
   * Units of measure for the summary value
   * </pre>
   *
   * <code>string units = 2;</code>
   * @return The units.
   */
  @java.lang.Override
  public java.lang.String getUnits() {
    java.lang.Object ref = units_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      units_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Units of measure for the summary value
   * </pre>
   *
   * <code>string units = 2;</code>
   * @return The bytes for units.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitsBytes() {
    java.lang.Object ref = units_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      units_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private long value_ = 0L;
  /**
   * <pre>
   * The value of the summary
   * </pre>
   *
   * <code>int64 value = 3;</code>
   * @return The value.
   */
  @java.lang.Override
  public long getValue() {
    return value_;
  }

  public static final int COUNT_FIELD_NUMBER = 4;
  private long count_ = 0L;
  /**
   * <pre>
   * The number of events included in the summary
   * </pre>
   *
   * <code>int64 count = 4;</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }

  public static final int CREDITS_FIELD_NUMBER = 5;
  private double credits_ = 0D;
  /**
   * <pre>
   * Credits used by this event
   * </pre>
   *
   * <code>double credits = 5;</code>
   * @return The credits.
   */
  @java.lang.Override
  public double getCredits() {
    return credits_;
  }

  public static final int TENANTID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
   * </pre>
   *
   * <code>string tenantId = 6;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
   * </pre>
   *
   * <code>string tenantId = 6;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (billableFunction_ != ai.sensorycloud.api.common.ModelType.UNKNOWN.getNumber()) {
      output.writeEnum(1, billableFunction_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(units_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, units_);
    }
    if (value_ != 0L) {
      output.writeInt64(3, value_);
    }
    if (count_ != 0L) {
      output.writeInt64(4, count_);
    }
    if (java.lang.Double.doubleToRawLongBits(credits_) != 0) {
      output.writeDouble(5, credits_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, tenantId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (billableFunction_ != ai.sensorycloud.api.common.ModelType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, billableFunction_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(units_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, units_);
    }
    if (value_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, value_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, count_);
    }
    if (java.lang.Double.doubleToRawLongBits(credits_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, credits_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, tenantId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sensorycloud.api.v1.event.UsageEventModelSummary)) {
      return super.equals(obj);
    }
    ai.sensorycloud.api.v1.event.UsageEventModelSummary other = (ai.sensorycloud.api.v1.event.UsageEventModelSummary) obj;

    if (billableFunction_ != other.billableFunction_) return false;
    if (!getUnits()
        .equals(other.getUnits())) return false;
    if (getValue()
        != other.getValue()) return false;
    if (getCount()
        != other.getCount()) return false;
    if (java.lang.Double.doubleToLongBits(getCredits())
        != java.lang.Double.doubleToLongBits(
            other.getCredits())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BILLABLEFUNCTION_FIELD_NUMBER;
    hash = (53 * hash) + billableFunction_;
    hash = (37 * hash) + UNITS_FIELD_NUMBER;
    hash = (53 * hash) + getUnits().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getValue());
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    hash = (37 * hash) + CREDITS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCredits()));
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.event.UsageEventModelSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sensory.api.v1.event.UsageEventModelSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.event.UsageEventModelSummary)
      ai.sensorycloud.api.v1.event.UsageEventModelSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sensorycloud.api.v1.event.SensoryApiV1EventProto.internal_static_sensory_api_v1_event_UsageEventModelSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sensorycloud.api.v1.event.SensoryApiV1EventProto.internal_static_sensory_api_v1_event_UsageEventModelSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sensorycloud.api.v1.event.UsageEventModelSummary.class, ai.sensorycloud.api.v1.event.UsageEventModelSummary.Builder.class);
    }

    // Construct using ai.sensorycloud.api.v1.event.UsageEventModelSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      billableFunction_ = 0;
      units_ = "";
      value_ = 0L;
      count_ = 0L;
      credits_ = 0D;
      tenantId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sensorycloud.api.v1.event.SensoryApiV1EventProto.internal_static_sensory_api_v1_event_UsageEventModelSummary_descriptor;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.event.UsageEventModelSummary getDefaultInstanceForType() {
      return ai.sensorycloud.api.v1.event.UsageEventModelSummary.getDefaultInstance();
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.event.UsageEventModelSummary build() {
      ai.sensorycloud.api.v1.event.UsageEventModelSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.event.UsageEventModelSummary buildPartial() {
      ai.sensorycloud.api.v1.event.UsageEventModelSummary result = new ai.sensorycloud.api.v1.event.UsageEventModelSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.sensorycloud.api.v1.event.UsageEventModelSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.billableFunction_ = billableFunction_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.units_ = units_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.value_ = value_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.count_ = count_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.credits_ = credits_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.tenantId_ = tenantId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sensorycloud.api.v1.event.UsageEventModelSummary) {
        return mergeFrom((ai.sensorycloud.api.v1.event.UsageEventModelSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sensorycloud.api.v1.event.UsageEventModelSummary other) {
      if (other == ai.sensorycloud.api.v1.event.UsageEventModelSummary.getDefaultInstance()) return this;
      if (other.billableFunction_ != 0) {
        setBillableFunctionValue(other.getBillableFunctionValue());
      }
      if (!other.getUnits().isEmpty()) {
        units_ = other.units_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getValue() != 0L) {
        setValue(other.getValue());
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      if (other.getCredits() != 0D) {
        setCredits(other.getCredits());
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              billableFunction_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              units_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              value_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              count_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 41: {
              credits_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int billableFunction_ = 0;
    /**
     * <pre>
     * Function of the model used
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
     * @return The enum numeric value on the wire for billableFunction.
     */
    @java.lang.Override public int getBillableFunctionValue() {
      return billableFunction_;
    }
    /**
     * <pre>
     * Function of the model used
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
     * @param value The enum numeric value on the wire for billableFunction to set.
     * @return This builder for chaining.
     */
    public Builder setBillableFunctionValue(int value) {
      billableFunction_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Function of the model used
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
     * @return The billableFunction.
     */
    @java.lang.Override
    public ai.sensorycloud.api.common.ModelType getBillableFunction() {
      ai.sensorycloud.api.common.ModelType result = ai.sensorycloud.api.common.ModelType.forNumber(billableFunction_);
      return result == null ? ai.sensorycloud.api.common.ModelType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Function of the model used
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
     * @param value The billableFunction to set.
     * @return This builder for chaining.
     */
    public Builder setBillableFunction(ai.sensorycloud.api.common.ModelType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      billableFunction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Function of the model used
     * </pre>
     *
     * <code>.sensory.api.common.ModelType billableFunction = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBillableFunction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      billableFunction_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object units_ = "";
    /**
     * <pre>
     * Units of measure for the summary value
     * </pre>
     *
     * <code>string units = 2;</code>
     * @return The units.
     */
    public java.lang.String getUnits() {
      java.lang.Object ref = units_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        units_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Units of measure for the summary value
     * </pre>
     *
     * <code>string units = 2;</code>
     * @return The bytes for units.
     */
    public com.google.protobuf.ByteString
        getUnitsBytes() {
      java.lang.Object ref = units_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        units_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Units of measure for the summary value
     * </pre>
     *
     * <code>string units = 2;</code>
     * @param value The units to set.
     * @return This builder for chaining.
     */
    public Builder setUnits(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      units_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Units of measure for the summary value
     * </pre>
     *
     * <code>string units = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnits() {
      units_ = getDefaultInstance().getUnits();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Units of measure for the summary value
     * </pre>
     *
     * <code>string units = 2;</code>
     * @param value The bytes for units to set.
     * @return This builder for chaining.
     */
    public Builder setUnitsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      units_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long value_ ;
    /**
     * <pre>
     * The value of the summary
     * </pre>
     *
     * <code>int64 value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }
    /**
     * <pre>
     * The value of the summary
     * </pre>
     *
     * <code>int64 value = 3;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(long value) {

      value_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The value of the summary
     * </pre>
     *
     * <code>int64 value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      value_ = 0L;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <pre>
     * The number of events included in the summary
     * </pre>
     *
     * <code>int64 count = 4;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * The number of events included in the summary
     * </pre>
     *
     * <code>int64 count = 4;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {

      count_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of events included in the summary
     * </pre>
     *
     * <code>int64 count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      count_ = 0L;
      onChanged();
      return this;
    }

    private double credits_ ;
    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 5;</code>
     * @return The credits.
     */
    @java.lang.Override
    public double getCredits() {
      return credits_;
    }
    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 5;</code>
     * @param value The credits to set.
     * @return This builder for chaining.
     */
    public Builder setCredits(double value) {

      credits_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Credits used by this event
     * </pre>
     *
     * <code>double credits = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredits() {
      bitField0_ = (bitField0_ & ~0x00000010);
      credits_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Tenant that the events are from. For summaries that span multiple tenants, this field will be empty
     * </pre>
     *
     * <code>string tenantId = 6;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensory.api.v1.event.UsageEventModelSummary)
  }

  // @@protoc_insertion_point(class_scope:sensory.api.v1.event.UsageEventModelSummary)
  private static final ai.sensorycloud.api.v1.event.UsageEventModelSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sensorycloud.api.v1.event.UsageEventModelSummary();
  }

  public static ai.sensorycloud.api.v1.event.UsageEventModelSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UsageEventModelSummary>
      PARSER = new com.google.protobuf.AbstractParser<UsageEventModelSummary>() {
    @java.lang.Override
    public UsageEventModelSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UsageEventModelSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UsageEventModelSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.sensorycloud.api.v1.event.UsageEventModelSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

