// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/assistant/assistant.proto

package ai.sensorycloud.api.v1.assistant;

public interface AssistantMessageConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.v1.assistant.AssistantMessageConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 3 [(.validate.rules) = { ... }</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 4 [(.validate.rules) = { ... }</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 4 [(.validate.rules) = { ... }</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <pre>
   * Indicates if audio content should be returned along with text and intent content
   * </pre>
   *
   * <code>bool includeAudioResponse = 5;</code>
   * @return The includeAudioResponse.
   */
  boolean getIncludeAudioResponse();
}
