// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/file/file.proto

package ai.sensorycloud.api.v1.file;

public final class SensoryApiV1FileProto {
  private SensoryApiV1FileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileCatalogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileCatalogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileCompleteCatalogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileCompleteCatalogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileCatalogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileCatalogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileChunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_FileCatalog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_FileCatalog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensory_api_v1_file_VersionedFileCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sensory_api_v1_file_VersionedFileCategory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022v1/file/file.proto\022\023sensory.api.v1.fil" +
      "e\032\027validate/validate.proto\"u\n\013FileReques" +
      "t\022\030\n\004file\030\001 \001(\tB\n\372B\007r\005\020\001\030\377\017\022<\n\010category\030" +
      "\002 \001(\0132*.sensory.api.v1.file.VersionedFil" +
      "eCategory\022\016\n\006offset\030\003 \001(\003\"\225\001\n\014FileRespon" +
      "se\022-\n\004info\030\001 \001(\0132\035.sensory.api.v1.file.F" +
      "ileInfoH\000\022/\n\005chunk\030\002 \001(\0132\036.sensory.api.v" +
      "1.file.FileChunkH\000\022\020\n\010complete\030\003 \001(\010B\023\n\021" +
      "streamingResponse\"^\n\022FileCatalogRequest\022" +
      "H\n\ncategories\030\001 \003(\0132*.sensory.api.v1.fil" +
      "e.VersionedFileCategoryB\010\372B\005\222\001\002\010\001\".\n\032Fil" +
      "eCompleteCatalogRequest\022\020\n\010tenantId\030\001 \001(" +
      "\t\"H\n\023FileCatalogResponse\0221\n\007catalog\030\001 \003(" +
      "\0132 .sensory.api.v1.file.FileCatalog\"*\n\tF" +
      "ileChunk\022\r\n\005bytes\030\001 \001(\014\022\016\n\006offset\030\002 \001(\003\"" +
      "q\n\010FileInfo\022\014\n\004file\030\001 \001(\t\022\024\n\014absolutePat" +
      "h\030\002 \001(\t\022\014\n\004size\030\003 \001(\003\022\023\n\013contentType\030\004 \001" +
      "(\t\022\014\n\004hash\030\005 \001(\t\022\020\n\010tenantId\030\006 \001(\t\"y\n\013Fi" +
      "leCatalog\022,\n\005files\030\001 \003(\0132\035.sensory.api.v" +
      "1.file.FileInfo\022<\n\010category\030\002 \001(\0132*.sens" +
      "ory.api.v1.file.VersionedFileCategory\"g\n" +
      "\025VersionedFileCategory\022=\n\010category\030\001 \001(\016" +
      "2!.sensory.api.v1.file.FileCategoryB\010\372B\005" +
      "\202\001\002\020\001\022\017\n\007version\030\002 \001(\t*K\n\014FileCategory\022\016" +
      "\n\nTSSV_MODEL\020\000\022\017\n\013ATLAS_MODEL\020\001\022\r\n\tTNL_M" +
      "ODEL\020\002\022\013\n\007UNKNOWN\020d2\377\002\n\004File\022L\n\007GetInfo\022" +
      " .sensory.api.v1.file.FileRequest\032\035.sens" +
      "ory.api.v1.file.FileInfo\"\000\022a\n\nGetCatalog" +
      "\022\'.sensory.api.v1.file.FileCatalogReques" +
      "t\032(.sensory.api.v1.file.FileCatalogRespo" +
      "nse\"\000\022q\n\022GetCompleteCatalog\022/.sensory.ap" +
      "i.v1.file.FileCompleteCatalogRequest\032(.s" +
      "ensory.api.v1.file.FileCatalogResponse\"\000" +
      "\022S\n\010Download\022 .sensory.api.v1.file.FileR" +
      "equest\032!.sensory.api.v1.file.FileRespons" +
      "e\"\0000\001Bx\n\033ai.sensorycloud.api.v1.fileB\025Se" +
      "nsoryApiV1FileProtoP\001Z9gitlab.com/sensor" +
      "y-cloud/server/titan.git/pkg/api/v1/file" +
      "\242\002\004SENGb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.envoyproxy.pgv.validate.Validate.getDescriptor(),
        });
    internal_static_sensory_api_v1_file_FileRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensory_api_v1_file_FileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileRequest_descriptor,
        new java.lang.String[] { "File", "Category", "Offset", });
    internal_static_sensory_api_v1_file_FileResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensory_api_v1_file_FileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileResponse_descriptor,
        new java.lang.String[] { "Info", "Chunk", "Complete", "StreamingResponse", });
    internal_static_sensory_api_v1_file_FileCatalogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sensory_api_v1_file_FileCatalogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileCatalogRequest_descriptor,
        new java.lang.String[] { "Categories", });
    internal_static_sensory_api_v1_file_FileCompleteCatalogRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sensory_api_v1_file_FileCompleteCatalogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileCompleteCatalogRequest_descriptor,
        new java.lang.String[] { "TenantId", });
    internal_static_sensory_api_v1_file_FileCatalogResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_sensory_api_v1_file_FileCatalogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileCatalogResponse_descriptor,
        new java.lang.String[] { "Catalog", });
    internal_static_sensory_api_v1_file_FileChunk_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_sensory_api_v1_file_FileChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileChunk_descriptor,
        new java.lang.String[] { "Bytes", "Offset", });
    internal_static_sensory_api_v1_file_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_sensory_api_v1_file_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileInfo_descriptor,
        new java.lang.String[] { "File", "AbsolutePath", "Size", "ContentType", "Hash", "TenantId", });
    internal_static_sensory_api_v1_file_FileCatalog_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_sensory_api_v1_file_FileCatalog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_FileCatalog_descriptor,
        new java.lang.String[] { "Files", "Category", });
    internal_static_sensory_api_v1_file_VersionedFileCategory_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_sensory_api_v1_file_VersionedFileCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sensory_api_v1_file_VersionedFileCategory_descriptor,
        new java.lang.String[] { "Category", "Version", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.envoyproxy.pgv.validate.Validate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
