// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oauth/oauth.proto

package ai.sensorycloud.api.oauth;

public interface WhoAmIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.oauth.WhoAmIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique client identifier created at enrollment
   * </pre>
   *
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Unique client identifier created at enrollment
   * </pre>
   *
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   * Unique tenant UUID for the particular client
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * Unique tenant UUID for the particular client
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
