// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/audio/audio.proto

package ai.sensorycloud.api.v1.audio;

public interface TranscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.v1.audio.TranscribeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Relative energy of the processed audio as a value between 0 and 1
   * </pre>
   *
   * <code>float audioEnergy = 1;</code>
   * @return The audioEnergy.
   */
  float getAudioEnergy();

  /**
   * <pre>
   * Text of the current transcript, sliding window on ~7 seconds
   * </pre>
   *
   * <code>string transcript = 2;</code>
   * @return The transcript.
   */
  java.lang.String getTranscript();
  /**
   * <pre>
   * Text of the current transcript, sliding window on ~7 seconds
   * </pre>
   *
   * <code>string transcript = 2;</code>
   * @return The bytes for transcript.
   */
  com.google.protobuf.ByteString
      getTranscriptBytes();

  /**
   * <pre>
   * Indicates if the returned transcript is an intermediate result
   * </pre>
   *
   * <code>bool isPartialResult = 3 [deprecated = true];</code>
   * @deprecated sensory.api.v1.audio.TranscribeResponse.isPartialResult is deprecated.
   *     See v1/audio/audio.proto;l=402
   * @return The isPartialResult.
   */
  @java.lang.Deprecated boolean getIsPartialResult();

  /**
   * <pre>
   * A response including word metadata
   * </pre>
   *
   * <code>.sensory.api.v1.audio.TranscribeWordResponse wordList = 4;</code>
   * @return Whether the wordList field is set.
   */
  boolean hasWordList();
  /**
   * <pre>
   * A response including word metadata
   * </pre>
   *
   * <code>.sensory.api.v1.audio.TranscribeWordResponse wordList = 4;</code>
   * @return The wordList.
   */
  ai.sensorycloud.api.v1.audio.TranscribeWordResponse getWordList();
  /**
   * <pre>
   * A response including word metadata
   * </pre>
   *
   * <code>.sensory.api.v1.audio.TranscribeWordResponse wordList = 4;</code>
   */
  ai.sensorycloud.api.v1.audio.TranscribeWordResponseOrBuilder getWordListOrBuilder();

  /**
   * <pre>
   * If a post processing audio action was requested, this will be populated with the specific
   * action that was completed along with the actionId optionally set by the client.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AudioResponsePostProcessingAction postProcessingAction = 10;</code>
   * @return Whether the postProcessingAction field is set.
   */
  boolean hasPostProcessingAction();
  /**
   * <pre>
   * If a post processing audio action was requested, this will be populated with the specific
   * action that was completed along with the actionId optionally set by the client.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AudioResponsePostProcessingAction postProcessingAction = 10;</code>
   * @return The postProcessingAction.
   */
  ai.sensorycloud.api.v1.audio.AudioResponsePostProcessingAction getPostProcessingAction();
  /**
   * <pre>
   * If a post processing audio action was requested, this will be populated with the specific
   * action that was completed along with the actionId optionally set by the client.
   * </pre>
   *
   * <code>.sensory.api.v1.audio.AudioResponsePostProcessingAction postProcessingAction = 10;</code>
   */
  ai.sensorycloud.api.v1.audio.AudioResponsePostProcessingActionOrBuilder getPostProcessingActionOrBuilder();
}
