// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/video/video.proto

package ai.sensorycloud.api.v1.video;

/**
 * <pre>
 * Response to an authentication request
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.video.AuthenticateResponse}
 */
public final class AuthenticateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.video.AuthenticateResponse)
    AuthenticateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthenticateResponse.newBuilder() to construct.
  private AuthenticateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthenticateResponse() {
    userId_ = "";
    enrollmentId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthenticateResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AuthenticateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 21: {

            score_ = input.readFloat();
            break;
          }
          case 24: {

            isAlive_ = input.readBool();
            break;
          }
          case 34: {
            ai.sensorycloud.api.common.TokenResponse.Builder subBuilder = null;
            if (token_ != null) {
              subBuilder = token_.toBuilder();
            }
            token_ = input.readMessage(ai.sensorycloud.api.common.TokenResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(token_);
              token_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            enrollmentId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_AuthenticateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_AuthenticateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sensorycloud.api.v1.video.AuthenticateResponse.class, ai.sensorycloud.api.v1.video.AuthenticateResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <pre>
   * Success / Failure bit
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int SCORE_FIELD_NUMBER = 2;
  private float score_;
  /**
   * <pre>
   * Score of the authentication (lower is better)
   * </pre>
   *
   * <code>float score = 2;</code>
   * @return The score.
   */
  @java.lang.Override
  public float getScore() {
    return score_;
  }

  public static final int ISALIVE_FIELD_NUMBER = 3;
  private boolean isAlive_;
  /**
   * <pre>
   * Liveness check bit. This value with always be false if 'isLivenessEnabled' is set to false in the AuthenticateConfig
   * </pre>
   *
   * <code>bool isAlive = 3;</code>
   * @return The isAlive.
   */
  @java.lang.Override
  public boolean getIsAlive() {
    return isAlive_;
  }

  public static final int TOKEN_FIELD_NUMBER = 4;
  private ai.sensorycloud.api.common.TokenResponse token_;
  /**
   * <pre>
   * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
   * </pre>
   *
   * <code>.sensory.api.common.TokenResponse token = 4;</code>
   * @return Whether the token field is set.
   */
  @java.lang.Override
  public boolean hasToken() {
    return token_ != null;
  }
  /**
   * <pre>
   * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
   * </pre>
   *
   * <code>.sensory.api.common.TokenResponse token = 4;</code>
   * @return The token.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.TokenResponse getToken() {
    return token_ == null ? ai.sensorycloud.api.common.TokenResponse.getDefaultInstance() : token_;
  }
  /**
   * <pre>
   * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
   * </pre>
   *
   * <code>.sensory.api.common.TokenResponse token = 4;</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.TokenResponseOrBuilder getTokenOrBuilder() {
    return getToken();
  }

  public static final int USERID_FIELD_NUMBER = 5;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   * The userID of the authenticated user
   * Useful when evaluating enrollment groups
   * </pre>
   *
   * <code>string userId = 5;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The userID of the authenticated user
   * Useful when evaluating enrollment groups
   * </pre>
   *
   * <code>string userId = 5;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENROLLMENTID_FIELD_NUMBER = 6;
  private volatile java.lang.Object enrollmentId_;
  /**
   * <pre>
   * The enrollment ID of the authenticated enrollment
   * Useful when evaluating enrollment groups
   * </pre>
   *
   * <code>string enrollmentId = 6;</code>
   * @return The enrollmentId.
   */
  @java.lang.Override
  public java.lang.String getEnrollmentId() {
    java.lang.Object ref = enrollmentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      enrollmentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The enrollment ID of the authenticated enrollment
   * Useful when evaluating enrollment groups
   * </pre>
   *
   * <code>string enrollmentId = 6;</code>
   * @return The bytes for enrollmentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnrollmentIdBytes() {
    java.lang.Object ref = enrollmentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      enrollmentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (java.lang.Float.floatToRawIntBits(score_) != 0) {
      output.writeFloat(2, score_);
    }
    if (isAlive_ != false) {
      output.writeBool(3, isAlive_);
    }
    if (token_ != null) {
      output.writeMessage(4, getToken());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(enrollmentId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, enrollmentId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (java.lang.Float.floatToRawIntBits(score_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, score_);
    }
    if (isAlive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isAlive_);
    }
    if (token_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getToken());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(enrollmentId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, enrollmentId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sensorycloud.api.v1.video.AuthenticateResponse)) {
      return super.equals(obj);
    }
    ai.sensorycloud.api.v1.video.AuthenticateResponse other = (ai.sensorycloud.api.v1.video.AuthenticateResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (java.lang.Float.floatToIntBits(getScore())
        != java.lang.Float.floatToIntBits(
            other.getScore())) return false;
    if (getIsAlive()
        != other.getIsAlive()) return false;
    if (hasToken() != other.hasToken()) return false;
    if (hasToken()) {
      if (!getToken()
          .equals(other.getToken())) return false;
    }
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getEnrollmentId()
        .equals(other.getEnrollmentId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getScore());
    hash = (37 * hash) + ISALIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsAlive());
    if (hasToken()) {
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
    }
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + ENROLLMENTID_FIELD_NUMBER;
    hash = (53 * hash) + getEnrollmentId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.video.AuthenticateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.video.AuthenticateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response to an authentication request
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.video.AuthenticateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.video.AuthenticateResponse)
      ai.sensorycloud.api.v1.video.AuthenticateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_AuthenticateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_AuthenticateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sensorycloud.api.v1.video.AuthenticateResponse.class, ai.sensorycloud.api.v1.video.AuthenticateResponse.Builder.class);
    }

    // Construct using ai.sensorycloud.api.v1.video.AuthenticateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      score_ = 0F;

      isAlive_ = false;

      if (tokenBuilder_ == null) {
        token_ = null;
      } else {
        token_ = null;
        tokenBuilder_ = null;
      }
      userId_ = "";

      enrollmentId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_AuthenticateResponse_descriptor;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.AuthenticateResponse getDefaultInstanceForType() {
      return ai.sensorycloud.api.v1.video.AuthenticateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.AuthenticateResponse build() {
      ai.sensorycloud.api.v1.video.AuthenticateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.AuthenticateResponse buildPartial() {
      ai.sensorycloud.api.v1.video.AuthenticateResponse result = new ai.sensorycloud.api.v1.video.AuthenticateResponse(this);
      result.success_ = success_;
      result.score_ = score_;
      result.isAlive_ = isAlive_;
      if (tokenBuilder_ == null) {
        result.token_ = token_;
      } else {
        result.token_ = tokenBuilder_.build();
      }
      result.userId_ = userId_;
      result.enrollmentId_ = enrollmentId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sensorycloud.api.v1.video.AuthenticateResponse) {
        return mergeFrom((ai.sensorycloud.api.v1.video.AuthenticateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sensorycloud.api.v1.video.AuthenticateResponse other) {
      if (other == ai.sensorycloud.api.v1.video.AuthenticateResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getScore() != 0F) {
        setScore(other.getScore());
      }
      if (other.getIsAlive() != false) {
        setIsAlive(other.getIsAlive());
      }
      if (other.hasToken()) {
        mergeToken(other.getToken());
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getEnrollmentId().isEmpty()) {
        enrollmentId_ = other.enrollmentId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sensorycloud.api.v1.video.AuthenticateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sensorycloud.api.v1.video.AuthenticateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <pre>
     * Success / Failure bit
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <pre>
     * Success / Failure bit
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Success / Failure bit
     * </pre>
     *
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private float score_ ;
    /**
     * <pre>
     * Score of the authentication (lower is better)
     * </pre>
     *
     * <code>float score = 2;</code>
     * @return The score.
     */
    @java.lang.Override
    public float getScore() {
      return score_;
    }
    /**
     * <pre>
     * Score of the authentication (lower is better)
     * </pre>
     *
     * <code>float score = 2;</code>
     * @param value The score to set.
     * @return This builder for chaining.
     */
    public Builder setScore(float value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Score of the authentication (lower is better)
     * </pre>
     *
     * <code>float score = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScore() {
      
      score_ = 0F;
      onChanged();
      return this;
    }

    private boolean isAlive_ ;
    /**
     * <pre>
     * Liveness check bit. This value with always be false if 'isLivenessEnabled' is set to false in the AuthenticateConfig
     * </pre>
     *
     * <code>bool isAlive = 3;</code>
     * @return The isAlive.
     */
    @java.lang.Override
    public boolean getIsAlive() {
      return isAlive_;
    }
    /**
     * <pre>
     * Liveness check bit. This value with always be false if 'isLivenessEnabled' is set to false in the AuthenticateConfig
     * </pre>
     *
     * <code>bool isAlive = 3;</code>
     * @param value The isAlive to set.
     * @return This builder for chaining.
     */
    public Builder setIsAlive(boolean value) {
      
      isAlive_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Liveness check bit. This value with always be false if 'isLivenessEnabled' is set to false in the AuthenticateConfig
     * </pre>
     *
     * <code>bool isAlive = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsAlive() {
      
      isAlive_ = false;
      onChanged();
      return this;
    }

    private ai.sensorycloud.api.common.TokenResponse token_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.TokenResponse, ai.sensorycloud.api.common.TokenResponse.Builder, ai.sensorycloud.api.common.TokenResponseOrBuilder> tokenBuilder_;
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     * @return Whether the token field is set.
     */
    public boolean hasToken() {
      return tokenBuilder_ != null || token_ != null;
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     * @return The token.
     */
    public ai.sensorycloud.api.common.TokenResponse getToken() {
      if (tokenBuilder_ == null) {
        return token_ == null ? ai.sensorycloud.api.common.TokenResponse.getDefaultInstance() : token_;
      } else {
        return tokenBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public Builder setToken(ai.sensorycloud.api.common.TokenResponse value) {
      if (tokenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        token_ = value;
        onChanged();
      } else {
        tokenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public Builder setToken(
        ai.sensorycloud.api.common.TokenResponse.Builder builderForValue) {
      if (tokenBuilder_ == null) {
        token_ = builderForValue.build();
        onChanged();
      } else {
        tokenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public Builder mergeToken(ai.sensorycloud.api.common.TokenResponse value) {
      if (tokenBuilder_ == null) {
        if (token_ != null) {
          token_ =
            ai.sensorycloud.api.common.TokenResponse.newBuilder(token_).mergeFrom(value).buildPartial();
        } else {
          token_ = value;
        }
        onChanged();
      } else {
        tokenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public Builder clearToken() {
      if (tokenBuilder_ == null) {
        token_ = null;
        onChanged();
      } else {
        token_ = null;
        tokenBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public ai.sensorycloud.api.common.TokenResponse.Builder getTokenBuilder() {
      
      onChanged();
      return getTokenFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    public ai.sensorycloud.api.common.TokenResponseOrBuilder getTokenOrBuilder() {
      if (tokenBuilder_ != null) {
        return tokenBuilder_.getMessageOrBuilder();
      } else {
        return token_ == null ?
            ai.sensorycloud.api.common.TokenResponse.getDefaultInstance() : token_;
      }
    }
    /**
     * <pre>
     * Optional token that will be returned upon a successful authentication if doIncludeToken is set to true in the AuthenticateConfig
     * </pre>
     *
     * <code>.sensory.api.common.TokenResponse token = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.TokenResponse, ai.sensorycloud.api.common.TokenResponse.Builder, ai.sensorycloud.api.common.TokenResponseOrBuilder> 
        getTokenFieldBuilder() {
      if (tokenBuilder_ == null) {
        tokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sensorycloud.api.common.TokenResponse, ai.sensorycloud.api.common.TokenResponse.Builder, ai.sensorycloud.api.common.TokenResponseOrBuilder>(
                getToken(),
                getParentForChildren(),
                isClean());
        token_ = null;
      }
      return tokenBuilder_;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * The userID of the authenticated user
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string userId = 5;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The userID of the authenticated user
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string userId = 5;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The userID of the authenticated user
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string userId = 5;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The userID of the authenticated user
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string userId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The userID of the authenticated user
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string userId = 5;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object enrollmentId_ = "";
    /**
     * <pre>
     * The enrollment ID of the authenticated enrollment
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string enrollmentId = 6;</code>
     * @return The enrollmentId.
     */
    public java.lang.String getEnrollmentId() {
      java.lang.Object ref = enrollmentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        enrollmentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The enrollment ID of the authenticated enrollment
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string enrollmentId = 6;</code>
     * @return The bytes for enrollmentId.
     */
    public com.google.protobuf.ByteString
        getEnrollmentIdBytes() {
      java.lang.Object ref = enrollmentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        enrollmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The enrollment ID of the authenticated enrollment
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string enrollmentId = 6;</code>
     * @param value The enrollmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnrollmentId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      enrollmentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The enrollment ID of the authenticated enrollment
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string enrollmentId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnrollmentId() {
      
      enrollmentId_ = getDefaultInstance().getEnrollmentId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The enrollment ID of the authenticated enrollment
     * Useful when evaluating enrollment groups
     * </pre>
     *
     * <code>string enrollmentId = 6;</code>
     * @param value The bytes for enrollmentId to set.
     * @return This builder for chaining.
     */
    public Builder setEnrollmentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      enrollmentId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensory.api.v1.video.AuthenticateResponse)
  }

  // @@protoc_insertion_point(class_scope:sensory.api.v1.video.AuthenticateResponse)
  private static final ai.sensorycloud.api.v1.video.AuthenticateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sensorycloud.api.v1.video.AuthenticateResponse();
  }

  public static ai.sensorycloud.api.v1.video.AuthenticateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthenticateResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthenticateResponse>() {
    @java.lang.Override
    public AuthenticateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AuthenticateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AuthenticateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthenticateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.sensorycloud.api.v1.video.AuthenticateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

