// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/video/video.proto

package ai.sensorycloud.api.v1.video;

/**
 * <pre>
 * Provides information for an enrollment
 * </pre>
 *
 * Protobuf type {@code sensory.api.v1.video.CreateEnrollmentConfig}
 */
public final class CreateEnrollmentConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensory.api.v1.video.CreateEnrollmentConfig)
    CreateEnrollmentConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateEnrollmentConfig.newBuilder() to construct.
  private CreateEnrollmentConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateEnrollmentConfig() {
    userId_ = "";
    deviceId_ = "";
    modelName_ = "";
    description_ = "";
    livenessThreshold_ = 0;
    referenceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateEnrollmentConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_CreateEnrollmentConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_CreateEnrollmentConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.class, ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique user Identifer. This value should be a unique email address or username known by the user.
   * </pre>
   *
   * <code>string userId = 1 [(.validate.rules) = { ... }</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
   * this value is used to identify a device uniquely across multiple enrollments
   * </pre>
   *
   * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODELNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modelName_ = "";
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @return The modelName.
   */
  @java.lang.Override
  public java.lang.String getModelName() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modelName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of background model to be enrolled in
   * Background models can be retrieved from the GetModels() gRPC call
   * </pre>
   *
   * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
   * @return The bytes for modelName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    java.lang.Object ref = modelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Description of the enrollment as entered by the user.
   * Max length is 1023 characters
   * </pre>
   *
   * <code>string description = 4 [(.validate.rules) = { ... }</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISLIVENESSENABLED_FIELD_NUMBER = 5;
  private boolean isLivenessEnabled_ = false;
  /**
   * <pre>
   * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
   * </pre>
   *
   * <code>bool isLivenessEnabled = 5;</code>
   * @return The isLivenessEnabled.
   */
  @java.lang.Override
  public boolean getIsLivenessEnabled() {
    return isLivenessEnabled_;
  }

  public static final int LIVENESSTHRESHOLD_FIELD_NUMBER = 6;
  private int livenessThreshold_ = 0;
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @return The enum numeric value on the wire for livenessThreshold.
   */
  @java.lang.Override public int getLivenessThresholdValue() {
    return livenessThreshold_;
  }
  /**
   * <pre>
   * The liveness threshold
   * </pre>
   *
   * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
   * @return The livenessThreshold.
   */
  @java.lang.Override public ai.sensorycloud.api.v1.video.RecognitionThreshold getLivenessThreshold() {
    ai.sensorycloud.api.v1.video.RecognitionThreshold result = ai.sensorycloud.api.v1.video.RecognitionThreshold.forNumber(livenessThreshold_);
    return result == null ? ai.sensorycloud.api.v1.video.RecognitionThreshold.UNRECOGNIZED : result;
  }

  public static final int COMPRESSION_FIELD_NUMBER = 7;
  private ai.sensorycloud.api.common.CompressionConfiguration compression_;
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   * @return Whether the compression field is set.
   */
  @java.lang.Override
  public boolean hasCompression() {
    return compression_ != null;
  }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   * @return The compression.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.CompressionConfiguration getCompression() {
    return compression_ == null ? ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance() : compression_;
  }
  /**
   * <pre>
   * Information about how the video data will be compressed.
   * </pre>
   *
   * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.CompressionConfigurationOrBuilder getCompressionOrBuilder() {
    return compression_ == null ? ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance() : compression_;
  }

  public static final int REFERENCEID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object referenceId_ = "";
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @return The referenceId.
   */
  @java.lang.Override
  public java.lang.String getReferenceId() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      referenceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Reference Id allows clients to assign their own identifier to enrollments for various purposes
   * such as tying an audio and video enrollment together.
   * </pre>
   *
   * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
   * @return The bytes for referenceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReferenceIdBytes() {
    java.lang.Object ref = referenceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      referenceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMLIVENESSFRAMESREQUIRED_FIELD_NUMBER = 9;
  private int numLivenessFramesRequired_ = 0;
  /**
   * <pre>
   * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
   * A value of 0 means that all enrollment frames must pass the liveness check.
   * </pre>
   *
   * <code>int32 numLivenessFramesRequired = 9;</code>
   * @return The numLivenessFramesRequired.
   */
  @java.lang.Override
  public int getNumLivenessFramesRequired() {
    return numLivenessFramesRequired_;
  }

  public static final int DISABLESERVERENROLLMENTTEMPLATESTORAGE_FIELD_NUMBER = 10;
  private boolean disableServerEnrollmentTemplateStorage_ = false;
  /**
   * <pre>
   * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
   * </pre>
   *
   * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
   * @return The disableServerEnrollmentTemplateStorage.
   */
  @java.lang.Override
  public boolean getDisableServerEnrollmentTemplateStorage() {
    return disableServerEnrollmentTemplateStorage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, modelName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (isLivenessEnabled_ != false) {
      output.writeBool(5, isLivenessEnabled_);
    }
    if (livenessThreshold_ != ai.sensorycloud.api.v1.video.RecognitionThreshold.LOW.getNumber()) {
      output.writeEnum(6, livenessThreshold_);
    }
    if (compression_ != null) {
      output.writeMessage(7, getCompression());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(referenceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, referenceId_);
    }
    if (numLivenessFramesRequired_ != 0) {
      output.writeInt32(9, numLivenessFramesRequired_);
    }
    if (disableServerEnrollmentTemplateStorage_ != false) {
      output.writeBool(10, disableServerEnrollmentTemplateStorage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modelName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, modelName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (isLivenessEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isLivenessEnabled_);
    }
    if (livenessThreshold_ != ai.sensorycloud.api.v1.video.RecognitionThreshold.LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, livenessThreshold_);
    }
    if (compression_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getCompression());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(referenceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, referenceId_);
    }
    if (numLivenessFramesRequired_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, numLivenessFramesRequired_);
    }
    if (disableServerEnrollmentTemplateStorage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, disableServerEnrollmentTemplateStorage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sensorycloud.api.v1.video.CreateEnrollmentConfig)) {
      return super.equals(obj);
    }
    ai.sensorycloud.api.v1.video.CreateEnrollmentConfig other = (ai.sensorycloud.api.v1.video.CreateEnrollmentConfig) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getModelName()
        .equals(other.getModelName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getIsLivenessEnabled()
        != other.getIsLivenessEnabled()) return false;
    if (livenessThreshold_ != other.livenessThreshold_) return false;
    if (hasCompression() != other.hasCompression()) return false;
    if (hasCompression()) {
      if (!getCompression()
          .equals(other.getCompression())) return false;
    }
    if (!getReferenceId()
        .equals(other.getReferenceId())) return false;
    if (getNumLivenessFramesRequired()
        != other.getNumLivenessFramesRequired()) return false;
    if (getDisableServerEnrollmentTemplateStorage()
        != other.getDisableServerEnrollmentTemplateStorage()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + MODELNAME_FIELD_NUMBER;
    hash = (53 * hash) + getModelName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + ISLIVENESSENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLivenessEnabled());
    hash = (37 * hash) + LIVENESSTHRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + livenessThreshold_;
    if (hasCompression()) {
      hash = (37 * hash) + COMPRESSION_FIELD_NUMBER;
      hash = (53 * hash) + getCompression().hashCode();
    }
    hash = (37 * hash) + REFERENCEID_FIELD_NUMBER;
    hash = (53 * hash) + getReferenceId().hashCode();
    hash = (37 * hash) + NUMLIVENESSFRAMESREQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + getNumLivenessFramesRequired();
    hash = (37 * hash) + DISABLESERVERENROLLMENTTEMPLATESTORAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableServerEnrollmentTemplateStorage());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.v1.video.CreateEnrollmentConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Provides information for an enrollment
   * </pre>
   *
   * Protobuf type {@code sensory.api.v1.video.CreateEnrollmentConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.v1.video.CreateEnrollmentConfig)
      ai.sensorycloud.api.v1.video.CreateEnrollmentConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_CreateEnrollmentConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_CreateEnrollmentConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.class, ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.Builder.class);
    }

    // Construct using ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      deviceId_ = "";
      modelName_ = "";
      description_ = "";
      isLivenessEnabled_ = false;
      livenessThreshold_ = 0;
      compression_ = null;
      if (compressionBuilder_ != null) {
        compressionBuilder_.dispose();
        compressionBuilder_ = null;
      }
      referenceId_ = "";
      numLivenessFramesRequired_ = 0;
      disableServerEnrollmentTemplateStorage_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sensorycloud.api.v1.video.SensoryApiV1VideoProto.internal_static_sensory_api_v1_video_CreateEnrollmentConfig_descriptor;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.CreateEnrollmentConfig getDefaultInstanceForType() {
      return ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.getDefaultInstance();
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.CreateEnrollmentConfig build() {
      ai.sensorycloud.api.v1.video.CreateEnrollmentConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.sensorycloud.api.v1.video.CreateEnrollmentConfig buildPartial() {
      ai.sensorycloud.api.v1.video.CreateEnrollmentConfig result = new ai.sensorycloud.api.v1.video.CreateEnrollmentConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.sensorycloud.api.v1.video.CreateEnrollmentConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.modelName_ = modelName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isLivenessEnabled_ = isLivenessEnabled_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.livenessThreshold_ = livenessThreshold_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.compression_ = compressionBuilder_ == null
            ? compression_
            : compressionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.referenceId_ = referenceId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.numLivenessFramesRequired_ = numLivenessFramesRequired_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.disableServerEnrollmentTemplateStorage_ = disableServerEnrollmentTemplateStorage_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sensorycloud.api.v1.video.CreateEnrollmentConfig) {
        return mergeFrom((ai.sensorycloud.api.v1.video.CreateEnrollmentConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sensorycloud.api.v1.video.CreateEnrollmentConfig other) {
      if (other == ai.sensorycloud.api.v1.video.CreateEnrollmentConfig.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getModelName().isEmpty()) {
        modelName_ = other.modelName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getIsLivenessEnabled() != false) {
        setIsLivenessEnabled(other.getIsLivenessEnabled());
      }
      if (other.livenessThreshold_ != 0) {
        setLivenessThresholdValue(other.getLivenessThresholdValue());
      }
      if (other.hasCompression()) {
        mergeCompression(other.getCompression());
      }
      if (!other.getReferenceId().isEmpty()) {
        referenceId_ = other.referenceId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getNumLivenessFramesRequired() != 0) {
        setNumLivenessFramesRequired(other.getNumLivenessFramesRequired());
      }
      if (other.getDisableServerEnrollmentTemplateStorage() != false) {
        setDisableServerEnrollmentTemplateStorage(other.getDisableServerEnrollmentTemplateStorage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              modelName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              isLivenessEnabled_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              livenessThreshold_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              input.readMessage(
                  getCompressionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              referenceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              numLivenessFramesRequired_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              disableServerEnrollmentTemplateStorage_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique user Identifer. This value should be a unique email address or username known by the user.
     * </pre>
     *
     * <code>string userId = 1 [(.validate.rules) = { ... }</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The unique device Identifer. This value should be something retrieved by the devie prior to enrollment (like MAC Address)
     * this value is used to identify a device uniquely across multiple enrollments
     * </pre>
     *
     * <code>string deviceId = 2 [(.validate.rules) = { ... }</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object modelName_ = "";
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return The modelName.
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return The bytes for modelName.
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @param value The modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modelName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearModelName() {
      modelName_ = getDefaultInstance().getModelName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of background model to be enrolled in
     * Background models can be retrieved from the GetModels() gRPC call
     * </pre>
     *
     * <code>string modelName = 3 [(.validate.rules) = { ... }</code>
     * @param value The bytes for modelName to set.
     * @return This builder for chaining.
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modelName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of the enrollment as entered by the user.
     * Max length is 1023 characters
     * </pre>
     *
     * <code>string description = 4 [(.validate.rules) = { ... }</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean isLivenessEnabled_ ;
    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @return The isLivenessEnabled.
     */
    @java.lang.Override
    public boolean getIsLivenessEnabled() {
      return isLivenessEnabled_;
    }
    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @param value The isLivenessEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsLivenessEnabled(boolean value) {

      isLivenessEnabled_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Enable a liveness check on the image, which will further improve the security of enrollment at the expense of a slightly slower response.
     * </pre>
     *
     * <code>bool isLivenessEnabled = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLivenessEnabled() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isLivenessEnabled_ = false;
      onChanged();
      return this;
    }

    private int livenessThreshold_ = 0;
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return The enum numeric value on the wire for livenessThreshold.
     */
    @java.lang.Override public int getLivenessThresholdValue() {
      return livenessThreshold_;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @param value The enum numeric value on the wire for livenessThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setLivenessThresholdValue(int value) {
      livenessThreshold_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return The livenessThreshold.
     */
    @java.lang.Override
    public ai.sensorycloud.api.v1.video.RecognitionThreshold getLivenessThreshold() {
      ai.sensorycloud.api.v1.video.RecognitionThreshold result = ai.sensorycloud.api.v1.video.RecognitionThreshold.forNumber(livenessThreshold_);
      return result == null ? ai.sensorycloud.api.v1.video.RecognitionThreshold.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @param value The livenessThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setLivenessThreshold(ai.sensorycloud.api.v1.video.RecognitionThreshold value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      livenessThreshold_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The liveness threshold
     * </pre>
     *
     * <code>.sensory.api.v1.video.RecognitionThreshold livenessThreshold = 6 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearLivenessThreshold() {
      bitField0_ = (bitField0_ & ~0x00000020);
      livenessThreshold_ = 0;
      onChanged();
      return this;
    }

    private ai.sensorycloud.api.common.CompressionConfiguration compression_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.CompressionConfiguration, ai.sensorycloud.api.common.CompressionConfiguration.Builder, ai.sensorycloud.api.common.CompressionConfigurationOrBuilder> compressionBuilder_;
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     * @return Whether the compression field is set.
     */
    public boolean hasCompression() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     * @return The compression.
     */
    public ai.sensorycloud.api.common.CompressionConfiguration getCompression() {
      if (compressionBuilder_ == null) {
        return compression_ == null ? ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance() : compression_;
      } else {
        return compressionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder setCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
      if (compressionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        compression_ = value;
      } else {
        compressionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder setCompression(
        ai.sensorycloud.api.common.CompressionConfiguration.Builder builderForValue) {
      if (compressionBuilder_ == null) {
        compression_ = builderForValue.build();
      } else {
        compressionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder mergeCompression(ai.sensorycloud.api.common.CompressionConfiguration value) {
      if (compressionBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          compression_ != null &&
          compression_ != ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance()) {
          getCompressionBuilder().mergeFrom(value);
        } else {
          compression_ = value;
        }
      } else {
        compressionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public Builder clearCompression() {
      bitField0_ = (bitField0_ & ~0x00000040);
      compression_ = null;
      if (compressionBuilder_ != null) {
        compressionBuilder_.dispose();
        compressionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public ai.sensorycloud.api.common.CompressionConfiguration.Builder getCompressionBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getCompressionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    public ai.sensorycloud.api.common.CompressionConfigurationOrBuilder getCompressionOrBuilder() {
      if (compressionBuilder_ != null) {
        return compressionBuilder_.getMessageOrBuilder();
      } else {
        return compression_ == null ?
            ai.sensorycloud.api.common.CompressionConfiguration.getDefaultInstance() : compression_;
      }
    }
    /**
     * <pre>
     * Information about how the video data will be compressed.
     * </pre>
     *
     * <code>.sensory.api.common.CompressionConfiguration compression = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.CompressionConfiguration, ai.sensorycloud.api.common.CompressionConfiguration.Builder, ai.sensorycloud.api.common.CompressionConfigurationOrBuilder> 
        getCompressionFieldBuilder() {
      if (compressionBuilder_ == null) {
        compressionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sensorycloud.api.common.CompressionConfiguration, ai.sensorycloud.api.common.CompressionConfiguration.Builder, ai.sensorycloud.api.common.CompressionConfigurationOrBuilder>(
                getCompression(),
                getParentForChildren(),
                isClean());
        compression_ = null;
      }
      return compressionBuilder_;
    }

    private java.lang.Object referenceId_ = "";
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return The referenceId.
     */
    public java.lang.String getReferenceId() {
      java.lang.Object ref = referenceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return The bytes for referenceId.
     */
    public com.google.protobuf.ByteString
        getReferenceIdBytes() {
      java.lang.Object ref = referenceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @param value The referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      referenceId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReferenceId() {
      referenceId_ = getDefaultInstance().getReferenceId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Reference Id allows clients to assign their own identifier to enrollments for various purposes
     * such as tying an audio and video enrollment together.
     * </pre>
     *
     * <code>string referenceId = 8 [(.validate.rules) = { ... }</code>
     * @param value The bytes for referenceId to set.
     * @return This builder for chaining.
     */
    public Builder setReferenceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      referenceId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int numLivenessFramesRequired_ ;
    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @return The numLivenessFramesRequired.
     */
    @java.lang.Override
    public int getNumLivenessFramesRequired() {
      return numLivenessFramesRequired_;
    }
    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @param value The numLivenessFramesRequired to set.
     * @return This builder for chaining.
     */
    public Builder setNumLivenessFramesRequired(int value) {

      numLivenessFramesRequired_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If isLivenessEnabled is true, this determines how many frames need to pass the liveness check before the enrollment can be successful
     * A value of 0 means that all enrollment frames must pass the liveness check.
     * </pre>
     *
     * <code>int32 numLivenessFramesRequired = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumLivenessFramesRequired() {
      bitField0_ = (bitField0_ & ~0x00000100);
      numLivenessFramesRequired_ = 0;
      onChanged();
      return this;
    }

    private boolean disableServerEnrollmentTemplateStorage_ ;
    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @return The disableServerEnrollmentTemplateStorage.
     */
    @java.lang.Override
    public boolean getDisableServerEnrollmentTemplateStorage() {
      return disableServerEnrollmentTemplateStorage_;
    }
    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @param value The disableServerEnrollmentTemplateStorage to set.
     * @return This builder for chaining.
     */
    public Builder setDisableServerEnrollmentTemplateStorage(boolean value) {

      disableServerEnrollmentTemplateStorage_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Prevent the server from storing the enrollment template. The template will be returned to the client for storage.
     * </pre>
     *
     * <code>bool disableServerEnrollmentTemplateStorage = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisableServerEnrollmentTemplateStorage() {
      bitField0_ = (bitField0_ & ~0x00000200);
      disableServerEnrollmentTemplateStorage_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensory.api.v1.video.CreateEnrollmentConfig)
  }

  // @@protoc_insertion_point(class_scope:sensory.api.v1.video.CreateEnrollmentConfig)
  private static final ai.sensorycloud.api.v1.video.CreateEnrollmentConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sensorycloud.api.v1.video.CreateEnrollmentConfig();
  }

  public static ai.sensorycloud.api.v1.video.CreateEnrollmentConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateEnrollmentConfig>
      PARSER = new com.google.protobuf.AbstractParser<CreateEnrollmentConfig>() {
    @java.lang.Override
    public CreateEnrollmentConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateEnrollmentConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateEnrollmentConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.sensorycloud.api.v1.video.CreateEnrollmentConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

