// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v1/video/video.proto

package ai.sensorycloud.api.v1.video;

public interface LivenessRecognitionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.v1.video.LivenessRecognitionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Success / Failure bit
   * </pre>
   *
   * <code>bool isAlive = 1;</code>
   * @return The isAlive.
   */
  boolean getIsAlive();

  /**
   * <pre>
   * Score of the liveness (lower is better)
   * </pre>
   *
   * <code>float score = 2;</code>
   * @return The score.
   */
  float getScore();

  /**
   * <pre>
   * Indicates if a face was found in the uploaded image
   * </pre>
   *
   * <code>bool didFindFace = 3;</code>
   * @return The didFindFace.
   */
  boolean getDidFindFace();

  /**
   * <pre>
   * The bounding box of the face
   * </pre>
   *
   * <code>repeated int64 boundingBox = 4;</code>
   * @return A list containing the boundingBox.
   */
  java.util.List<java.lang.Long> getBoundingBoxList();
  /**
   * <pre>
   * The bounding box of the face
   * </pre>
   *
   * <code>repeated int64 boundingBox = 4;</code>
   * @return The count of boundingBox.
   */
  int getBoundingBoxCount();
  /**
   * <pre>
   * The bounding box of the face
   * </pre>
   *
   * <code>repeated int64 boundingBox = 4;</code>
   * @param index The index of the element to return.
   * @return The boundingBox at the given index.
   */
  long getBoundingBox(int index);

  /**
   * <pre>
   * The model's confidence in its face detection
   * </pre>
   *
   * <code>float probabilityFace = 5;</code>
   * @return The probabilityFace.
   */
  float getProbabilityFace();
}
