// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package ai.sensorycloud.api.common;

public interface PaginationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sensory.api.common.PaginationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @return The ordering.
   */
  java.lang.String getOrdering();
  /**
   * <pre>
   * The parameter by which the data has been ordered by
   * </pre>
   *
   * <code>string ordering = 1;</code>
   * @return The bytes for ordering.
   */
  com.google.protobuf.ByteString
      getOrderingBytes();

  /**
   * <pre>
   * "True" if the data has been sorted in decending order
   * </pre>
   *
   * <code>bool decending = 2;</code>
   * @return The decending.
   */
  boolean getDecending();

  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @return A list containing the possibleOrderings.
   */
  java.util.List<java.lang.String>
      getPossibleOrderingsList();
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @return The count of possibleOrderings.
   */
  int getPossibleOrderingsCount();
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param index The index of the element to return.
   * @return The possibleOrderings at the given index.
   */
  java.lang.String getPossibleOrderings(int index);
  /**
   * <pre>
   * A list of all possible parameters that the data can be ordered by
   * </pre>
   *
   * <code>repeated string possibleOrderings = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the possibleOrderings at the given index.
   */
  com.google.protobuf.ByteString
      getPossibleOrderingsBytes(int index);

  /**
   * <pre>
   * The total count of data objects
   * </pre>
   *
   * <code>int64 totalCount = 4;</code>
   * @return The totalCount.
   */
  long getTotalCount();

  /**
   * <pre>
   * The page size of the data
   * </pre>
   *
   * <code>int32 pageSize = 5;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * The page index for the previous page. If negative there is no previous page
   * </pre>
   *
   * <code>int32 prevPageIndex = 6;</code>
   * @return The prevPageIndex.
   */
  int getPrevPageIndex();

  /**
   * <pre>
   * The page index for the current page.
   * </pre>
   *
   * <code>int32 currentPageIndex = 7;</code>
   * @return The currentPageIndex.
   */
  int getCurrentPageIndex();

  /**
   * <pre>
   * The page index for the next page. If negative there is no next page
   * </pre>
   *
   * <code>int32 nextPageIndex = 8;</code>
   * @return The nextPageIndex.
   */
  int getNextPageIndex();
}
