// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/common.proto

package ai.sensorycloud.api.common;

/**
 * <pre>
 * A summary of system statistics
 * </pre>
 *
 * Protobuf type {@code sensory.api.common.SystemSummary}
 */
public final class SystemSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sensory.api.common.SystemSummary)
    SystemSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SystemSummary.newBuilder() to construct.
  private SystemSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SystemSummary() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SystemSummary();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sensorycloud.api.common.SensoryApiCommonProto.internal_static_sensory_api_common_SystemSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sensorycloud.api.common.SensoryApiCommonProto.internal_static_sensory_api_common_SystemSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sensorycloud.api.common.SystemSummary.class, ai.sensorycloud.api.common.SystemSummary.Builder.class);
  }

  public static final int CPU_FIELD_NUMBER = 1;
  private ai.sensorycloud.api.common.CpuSummary cpu_;
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   * @return Whether the cpu field is set.
   */
  @java.lang.Override
  public boolean hasCpu() {
    return cpu_ != null;
  }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   * @return The cpu.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.CpuSummary getCpu() {
    return cpu_ == null ? ai.sensorycloud.api.common.CpuSummary.getDefaultInstance() : cpu_;
  }
  /**
   * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.CpuSummaryOrBuilder getCpuOrBuilder() {
    return cpu_ == null ? ai.sensorycloud.api.common.CpuSummary.getDefaultInstance() : cpu_;
  }

  public static final int MEMORY_FIELD_NUMBER = 2;
  private ai.sensorycloud.api.common.MemorySummary memory_;
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   * @return Whether the memory field is set.
   */
  @java.lang.Override
  public boolean hasMemory() {
    return memory_ != null;
  }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   * @return The memory.
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.MemorySummary getMemory() {
    return memory_ == null ? ai.sensorycloud.api.common.MemorySummary.getDefaultInstance() : memory_;
  }
  /**
   * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public ai.sensorycloud.api.common.MemorySummaryOrBuilder getMemoryOrBuilder() {
    return memory_ == null ? ai.sensorycloud.api.common.MemorySummary.getDefaultInstance() : memory_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cpu_ != null) {
      output.writeMessage(1, getCpu());
    }
    if (memory_ != null) {
      output.writeMessage(2, getMemory());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cpu_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCpu());
    }
    if (memory_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMemory());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.sensorycloud.api.common.SystemSummary)) {
      return super.equals(obj);
    }
    ai.sensorycloud.api.common.SystemSummary other = (ai.sensorycloud.api.common.SystemSummary) obj;

    if (hasCpu() != other.hasCpu()) return false;
    if (hasCpu()) {
      if (!getCpu()
          .equals(other.getCpu())) return false;
    }
    if (hasMemory() != other.hasMemory()) return false;
    if (hasMemory()) {
      if (!getMemory()
          .equals(other.getMemory())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCpu()) {
      hash = (37 * hash) + CPU_FIELD_NUMBER;
      hash = (53 * hash) + getCpu().hashCode();
    }
    if (hasMemory()) {
      hash = (37 * hash) + MEMORY_FIELD_NUMBER;
      hash = (53 * hash) + getMemory().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.sensorycloud.api.common.SystemSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.sensorycloud.api.common.SystemSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.sensorycloud.api.common.SystemSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.sensorycloud.api.common.SystemSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A summary of system statistics
   * </pre>
   *
   * Protobuf type {@code sensory.api.common.SystemSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sensory.api.common.SystemSummary)
      ai.sensorycloud.api.common.SystemSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sensorycloud.api.common.SensoryApiCommonProto.internal_static_sensory_api_common_SystemSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sensorycloud.api.common.SensoryApiCommonProto.internal_static_sensory_api_common_SystemSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sensorycloud.api.common.SystemSummary.class, ai.sensorycloud.api.common.SystemSummary.Builder.class);
    }

    // Construct using ai.sensorycloud.api.common.SystemSummary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cpu_ = null;
      if (cpuBuilder_ != null) {
        cpuBuilder_.dispose();
        cpuBuilder_ = null;
      }
      memory_ = null;
      if (memoryBuilder_ != null) {
        memoryBuilder_.dispose();
        memoryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sensorycloud.api.common.SensoryApiCommonProto.internal_static_sensory_api_common_SystemSummary_descriptor;
    }

    @java.lang.Override
    public ai.sensorycloud.api.common.SystemSummary getDefaultInstanceForType() {
      return ai.sensorycloud.api.common.SystemSummary.getDefaultInstance();
    }

    @java.lang.Override
    public ai.sensorycloud.api.common.SystemSummary build() {
      ai.sensorycloud.api.common.SystemSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.sensorycloud.api.common.SystemSummary buildPartial() {
      ai.sensorycloud.api.common.SystemSummary result = new ai.sensorycloud.api.common.SystemSummary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.sensorycloud.api.common.SystemSummary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cpu_ = cpuBuilder_ == null
            ? cpu_
            : cpuBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.memory_ = memoryBuilder_ == null
            ? memory_
            : memoryBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sensorycloud.api.common.SystemSummary) {
        return mergeFrom((ai.sensorycloud.api.common.SystemSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sensorycloud.api.common.SystemSummary other) {
      if (other == ai.sensorycloud.api.common.SystemSummary.getDefaultInstance()) return this;
      if (other.hasCpu()) {
        mergeCpu(other.getCpu());
      }
      if (other.hasMemory()) {
        mergeMemory(other.getMemory());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCpuFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMemoryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ai.sensorycloud.api.common.CpuSummary cpu_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.CpuSummary, ai.sensorycloud.api.common.CpuSummary.Builder, ai.sensorycloud.api.common.CpuSummaryOrBuilder> cpuBuilder_;
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     * @return Whether the cpu field is set.
     */
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     * @return The cpu.
     */
    public ai.sensorycloud.api.common.CpuSummary getCpu() {
      if (cpuBuilder_ == null) {
        return cpu_ == null ? ai.sensorycloud.api.common.CpuSummary.getDefaultInstance() : cpu_;
      } else {
        return cpuBuilder_.getMessage();
      }
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCpu(ai.sensorycloud.api.common.CpuSummary value) {
      if (cpuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cpu_ = value;
      } else {
        cpuBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder setCpu(
        ai.sensorycloud.api.common.CpuSummary.Builder builderForValue) {
      if (cpuBuilder_ == null) {
        cpu_ = builderForValue.build();
      } else {
        cpuBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeCpu(ai.sensorycloud.api.common.CpuSummary value) {
      if (cpuBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          cpu_ != null &&
          cpu_ != ai.sensorycloud.api.common.CpuSummary.getDefaultInstance()) {
          getCpuBuilder().mergeFrom(value);
        } else {
          cpu_ = value;
        }
      } else {
        cpuBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public Builder clearCpu() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cpu_ = null;
      if (cpuBuilder_ != null) {
        cpuBuilder_.dispose();
        cpuBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.CpuSummary.Builder getCpuBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCpuFieldBuilder().getBuilder();
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.CpuSummaryOrBuilder getCpuOrBuilder() {
      if (cpuBuilder_ != null) {
        return cpuBuilder_.getMessageOrBuilder();
      } else {
        return cpu_ == null ?
            ai.sensorycloud.api.common.CpuSummary.getDefaultInstance() : cpu_;
      }
    }
    /**
     * <code>.sensory.api.common.CpuSummary cpu = 1 [(.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.CpuSummary, ai.sensorycloud.api.common.CpuSummary.Builder, ai.sensorycloud.api.common.CpuSummaryOrBuilder> 
        getCpuFieldBuilder() {
      if (cpuBuilder_ == null) {
        cpuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sensorycloud.api.common.CpuSummary, ai.sensorycloud.api.common.CpuSummary.Builder, ai.sensorycloud.api.common.CpuSummaryOrBuilder>(
                getCpu(),
                getParentForChildren(),
                isClean());
        cpu_ = null;
      }
      return cpuBuilder_;
    }

    private ai.sensorycloud.api.common.MemorySummary memory_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.MemorySummary, ai.sensorycloud.api.common.MemorySummary.Builder, ai.sensorycloud.api.common.MemorySummaryOrBuilder> memoryBuilder_;
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     * @return Whether the memory field is set.
     */
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     * @return The memory.
     */
    public ai.sensorycloud.api.common.MemorySummary getMemory() {
      if (memoryBuilder_ == null) {
        return memory_ == null ? ai.sensorycloud.api.common.MemorySummary.getDefaultInstance() : memory_;
      } else {
        return memoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder setMemory(ai.sensorycloud.api.common.MemorySummary value) {
      if (memoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        memory_ = value;
      } else {
        memoryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder setMemory(
        ai.sensorycloud.api.common.MemorySummary.Builder builderForValue) {
      if (memoryBuilder_ == null) {
        memory_ = builderForValue.build();
      } else {
        memoryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder mergeMemory(ai.sensorycloud.api.common.MemorySummary value) {
      if (memoryBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          memory_ != null &&
          memory_ != ai.sensorycloud.api.common.MemorySummary.getDefaultInstance()) {
          getMemoryBuilder().mergeFrom(value);
        } else {
          memory_ = value;
        }
      } else {
        memoryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public Builder clearMemory() {
      bitField0_ = (bitField0_ & ~0x00000002);
      memory_ = null;
      if (memoryBuilder_ != null) {
        memoryBuilder_.dispose();
        memoryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.MemorySummary.Builder getMemoryBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMemoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    public ai.sensorycloud.api.common.MemorySummaryOrBuilder getMemoryOrBuilder() {
      if (memoryBuilder_ != null) {
        return memoryBuilder_.getMessageOrBuilder();
      } else {
        return memory_ == null ?
            ai.sensorycloud.api.common.MemorySummary.getDefaultInstance() : memory_;
      }
    }
    /**
     * <code>.sensory.api.common.MemorySummary memory = 2 [(.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.sensorycloud.api.common.MemorySummary, ai.sensorycloud.api.common.MemorySummary.Builder, ai.sensorycloud.api.common.MemorySummaryOrBuilder> 
        getMemoryFieldBuilder() {
      if (memoryBuilder_ == null) {
        memoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.sensorycloud.api.common.MemorySummary, ai.sensorycloud.api.common.MemorySummary.Builder, ai.sensorycloud.api.common.MemorySummaryOrBuilder>(
                getMemory(),
                getParentForChildren(),
                isClean());
        memory_ = null;
      }
      return memoryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sensory.api.common.SystemSummary)
  }

  // @@protoc_insertion_point(class_scope:sensory.api.common.SystemSummary)
  private static final ai.sensorycloud.api.common.SystemSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.sensorycloud.api.common.SystemSummary();
  }

  public static ai.sensorycloud.api.common.SystemSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SystemSummary>
      PARSER = new com.google.protobuf.AbstractParser<SystemSummary>() {
    @java.lang.Override
    public SystemSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SystemSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SystemSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.sensorycloud.api.common.SystemSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

